#!/bin/sh
#
# AUTHOR: S.S.R. Oemrawsingh
#
# DATE: Sat Nov 07 2009
#
# DESC: Elvi to search FACEBOOK
# elvis: facebook		-- Search FACEBOOK (www.facebook.com)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search FACEBOOK (www.facebook.com) for videos
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
# if test -z "$w3_args"; then
    w3_browse_url "http://www.facebook.com/"
# else
#     escaped_args=`w3_url_of_arg $w3_args`
#     w3_browse_url "http://www.facebook.com/results?search_query=${escaped_args}"
# fi