#!/bin/sh
#
# AUTHOR: S.S.R. Oemrawsingh
#
# DATE: Sat Nov 07 2009
#
# DESC: Elvi to search NSBUILD
# elvis: nsbuild		-- Search NSBUILD (www.nsbuild.rs)
. surfraw || exit 1

w3_usage_hook () {
    cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search NSBUILD (www.nsbuild.com) for videos
EOF
    w3_global_usage
}

w3_config
w3_parse_args "$@"
# if test -z "$w3_args"; then
    w3_browse_url "http://www.nsbuild.rs/"
# else
#     escaped_args=`w3_url_of_arg $w3_args`
#     w3_browse_url "http://www.nsbuild.rs/results?search_query=${escaped_args}"
# fi