#!/usr/bin/env python
from git import Repo
import os, sys
from rofi_dir_man import invoke_dir_man


def format_repo_url(url: str) -> str:
    if url[-1] == "/":
        url = url[0:-2]
    if not url.endswith(".git"):
        url += ".git"
    return url


def get_repo_name_from_url(url: str) -> str:
    last_slash_index = url.rfind("/")
    last_suffix_index = url.rfind(".git")
    if last_suffix_index < 0:
        last_suffix_index = len(url)

    if last_slash_index < 0 or last_suffix_index <= last_slash_index:
        raise Exception("Badly formatted url {}".format(url))

    return url[last_slash_index + 1:last_suffix_index]


default_path = "/tools/git_repos"
repo = sys.argv[1]

if len(sys.argv) == 2:
    path = invoke_dir_man(default_path)
elif len(sys.argv) == 3:
    use_default = sys.argv[2]
    if use_default == "default":
        path = default_path
    else:
        path = invoke_dir_man(default_path)

repo = format_repo_url(repo)
repo_name = get_repo_name_from_url(repo)
path = os.path.join(path, repo_name)

Repo.clone_from(repo, path)
