#! /bin/sh

WIDTH=${WIDTH:200}
HEIGHT=${HEIGHT:200}
DATEFMT=${DATEFMT:-"+%d.%m.%Y  %H:%M"}
SHORTFMT=${SHORTFMT:-"+%H:%M:%S"}

OPTIND=1

while getopts ":f:W:H:" opt; do
    case $opt in
        f) DATEFMT="$OPTARG" ;;
        W) WIDTH="$OPTARG" ;;
        H) HEIGHT="$OPTARG" ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            exit 1
            ;;
        :)
            echo "Option -$OPTARG requires an argument." >&2
            exit 1
            ;;
    esac
done
case "$BLOCK_BUTTON" in
  1|2|3)

 # TODO make it to work with just 1 display

      # screen1_width=$(xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f1 | sed -n 1p)
      # screen2_width=$(xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f1 | sed -n 2p)
      # screen1_height=$(xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f2 | sed -n 1p)
      # screen2_height=$(xrandr --current | grep '*' | uniq | awk '{print $1}' | cut -d 'x' -f2 | sed -n 2p)

      # mouse_pos_x=$(xdotool getmouselocation --shell | grep X= | tr -d 'X=')
      # mouse_pos_y=$(xdotool getmouselocation --shell | grep Y= | tr -d 'Y=')

      # if [ $mouse_pos_x -gt $screen1_width ]
      # then
      #     posX=$(($screen1_width + $screen2_width - 227))
      #     posY=$(($screen2_height - 221))
      # elif [ $mouse_pos_x -lt $screen1_width ]
      # then
      #     posX=$(($screen1_width  - 227))
      #     posY=$(($screen1_height - 221))
      # fi
	exec yad --calendar --undecorated --fixed --close-on-unfocus --no-buttons

	# i3-msg -q "exec yad --calendar \
  #       --width=$WIDTH --height=$HEIGHT \
	#     --undecorated --fixed \
	#     --close-on-unfocus --no-buttons \
	#     --posx=$posX-40 --posy=$posY-40 \
	#     > /dev/null"
esac
date "$DATEFMT"
date "$SHORTFMT"
